lines = join(readlines("linear_algebra_systems.qmd", keep=true));

lines = replace(lines, ":::{proof:theorem}" => ":::{#thm-}")
lines = replace(lines, ":::{proof:definition}"=> ":::{#def-}")
lines = replace(lines, ":::{proof:example}" => ":::{#exm-}")
lines = replace(lines, ":::{proof:example}" => ":::{#exm-}")
lines = replace(lines, ":::{proof:proof}" => ":::{.proof}")
lines = replace(lines, ":::{dropdown} Solution" => ":::{.solution}")
lines = replace(lines, r":::{math}\r?\n([\s\S]*?)\r?\n:::" => s"$$\n\1\n$$")
lines = replace(lines, r"{eq}`([^`]*)`" => s"@\1")
lines = replace(lines, r"{numref}`([^`]*)`" => s"@\1")
lines = replace(lines, r"```{math}([^`]*)```" => s"$$\1$$")
lines = replace(lines, r"````?{proof:theorem}(.*)\r?\n([\s\S]*?)\r?\n````?" => s"::::{#thm-}\n# \1\n\2\n::::")
lines = replace(lines, r"````{proof:definition}([^`]*)````" => s"::::{#def-}\1::::")
lines = replace(lines, r"^```({index}[^`]*)```" => s"<!--\1-->")
lines = replace(lines, r"```{note}([^`]*)```" => s":::{.callout-note}\1:::")
lines = replace(lines, ":::{note}" => ":::{.callout-note}")
lines = replace(lines, r"```{attention}([^`]*)```" => s":::{.callout-attention}\1:::")
lines = replace(lines, ":::{attention}" => ":::{.callout-attention}")
lines = replace(lines, r"```{warning}([^`]*)```" => s":::{.callout-warning}\1:::")
lines = replace(lines, ":::{warning}" => ":::{.callout-warning}")
lines = replace(lines, r"```{tip}([^`]*)```" => s":::{.callout-tip}\1:::")
lines = replace(lines, ":::{tip}" => ":::{.callout-tip}")
lines = replace(lines, r":label: eq([^\n]*)\n([^\$]*)\$\$"=> s"\2$$ {#eq\1}")
